### ISSUE TITLE
Security Vulnerability Analysis

### ISSUE THREAD

**Issue by afjoseph** [idnow/de.idnow.android#17]
Hey. I was testing your SDK and noticed a couple of things I'd like to report. Maybe you guys are aware of this or not but I just wanted to mention it regardless :)

# Hostname Verifier in `IdNowOkHttpFactory.java`
Its appears that you are using a custom verifier for OkHttp. This is reported as a security vulnerability. Developer.google.com says:

```
The more drastic alternative is to replace HostnameVerifier with one that uses not the hostname of your virtual host, but the one returned by the server by default.
```
source: http://developer.android.com/training/articles/security-ssl.html 

Also [OWASP Mobile Top 10 reports](https://www.owasp.org/index.php/Mobile_Top_10_2014-M3) it as an issue and [this book as well](http://goo.gl/BFb65r).

# Overriding `X509Certificate` in `IdNowOkHttpFactory.java`
Can you help me understand the reason that X509Certificates are overridden in here `Lde/idnow/sdk/IDnowOkHttpFactory;->customTrustManager()[Ljavax/net/ssl/TrustManager;`?
This could be problematic: https://www.securecoding.cert.org/confluence/pages/viewpage.action?pageId=134807561

# Webview local file access
`setAllowFileAccess()` is true by default with webviews. The attackers could inject malicious script into WebView and exploit the opportunity to access local resources. It would be best to set the flag as false if its not used by the webview like this: `yourWebView.getSettings().setAllowFileAccess(false)`

Reference: 
- https://labs.mwrinfosecurity.com/blog/2012/04/23/adventures-with-android-webviews/
-
 http://developer.android.com/reference/android/webkit/WebSettings.html#setAllowFileAccess(boolean)

# `Util_Jailbreaking.java`
I didn't understand the use of this one. It tries to read system data. I don't see the reason this is necessary at all.

**Comment by dmarjanovic** [comment]
Dear IDnow, is there any feedback on this security issue?

**Comment by aare-undo-idnow** [comment]
Hi! I understand that this issue is pretty old, and I will be closing this. However, these concerns seem to have been valid, so I still want to address them:

- Custom host name verifier is only used when http requests are allowed, which should never be the case for production apps anyway. Possibly implemented for debug environments
- The overridden `X509Certificate` is only ever used when invalid certificates are allowed. It's been lost to time why this was implemented, possibly for debug reasons.
- `setAllowFileAccess` was required for certain legacy Android OS permissions. It's no longer the case
- `Util_Jailbreaking` was used to check whether a device is rooted. For security reasons, checking whether a phone has been rooted was necessary. It's no longer being used
